# GitHub org of the repository (optional, `rust-lang` is the default)
org = "makai410"
# Name of the repository
repo = "rustc_public"
# Path where the subtree is located in rust-lang/rust
# path = "compiler/rustc_public"

# Optionally, you can specify the complete Josh filter for complex cases
# Note that this option is mutually exclusive with `path`
filter = ":rev(9b1a30e5e69e1537ef6eb6eb829eb47075206dea:prefix=compiler/rustc_public):/compiler/rustc_public"