[package]
name = "rpub-demo"
description = "A little demo tool on how to use rustc_public to analyze crates"
version = "0.0.0"
edition = "2021"

[dependencies]
rustc_public = { path = "../rustc_public", features = ["rustc_internal"] }

[package.metadata.rust-analyzer]
# This crate uses #[feature(rustc_private)].
# See https://github.com/rust-analyzer/rust-analyzer/pull/7891
rustc_private = true
