# Run a job to ensure Demo is OK
name: Run demo
on:
  pull_request:
    paths:
      - demo/**

  push:
    paths:
      - demo/**

jobs:
  check_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Demo
        run: ./demo/run_demo.sh
