name: Run compiler tests

on:
  schedule:
    - cron: "0 6 * * *"  # Run daily at 06:00 UTC
  workflow_dispatch:     # Allow manual dispatching
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  msrv:
    name: MSRV Nightly Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          # Note that this is the release date, which means the downloaded version is 2025-07-24.
          toolchain: nightly-2025-07-25
          components: rust-src
      - run: ./x test

  latest:
    name: Latest Nightly Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - run: ./x test
